### ISSUE TITLE
Villager not breeding

### ISSUE THREAD

**Issue by VRCapstone** [kyber-6/fantasymc-fabric-modpack#25]
### Describe the Bug

Whenever food is dropped near villagers they gather around and stare at the food but won't actually pick it up

### Screenshots

https://github.com/pixeldreamstudios/FantasyMinecraft/assets/57269151/e2568ee0-6a22-436d-a027-6ae49e538c17

### Modpack Version

v12.6

**Comment by KevzCz** [comment]
fixed
