### ISSUE TITLE
Stick creates Adamantite Longsword in crafting recipe

### ISSUE THREAD

**Issue by Pufficles** [kyber-6/fantasymc-fabric-modpack#29]
### Describe the bug

Placing a stick into the crafting window will give you an adamantite longsword. pretty sure this isnt intentional

### Reproduction Steps

acquire stick
place into any crafting window (inventory, crafting table)
adamantite longsword appears

### Screenshots

![2023-07-22_14 48 47](https://github.com/pixeldreamstudios/FantasyMC/assets/7377298/5ff667be-0009-4f43-bbc8-238c6437c2ee)

### Mod pack version

14.3

**Comment by KevzCz** [comment]
fixed now

**Comment by KevzCz** [comment]
fixed now
