### ISSUE TITLE
fantasy minecraft

### ISSUE THREAD

**Issue by Genetek18** [kyber-6/fantasymc-fabric-modpack#31]
### Describe the bug

I have no idea what happened, i lost my xp bar, it has just straight up disappeared. 

### Reproduction Steps

i dont know

### Screenshots

![image](https://github.com/kyber-6/fantasymc-fabric-modpack/assets/142568907/d71e6233-1077-495b-8d30-32b37d3cadf1)

### Mod pack version

14.3

**Comment by KevzCz** [comment]
There were issues about this on discord back then but since i havent heard anything about it for some time, i assume its been fixed by one of the mod updates
