### ISSUE TITLE
An Quest Revamp!

### ISSUE THREAD

**Issue by OviteHenry** [kyber-6/fantasymc-fabric-modpack#33]
### Describe your suggestion

One of the things that made me so invested in the modpack was the quest system, I think a good quest system is very important for an modpack, and this one is really great! But I DO think it could be more organized. Some quests have duplicate tasks (specially in the story mode chapter), and in my opinion, I think some quests should be a bit more engaging to do (like the Minecraft Story Mode armors, which I do think could have more interesting tasks). I tried to remake some chapters in this modpack so you can better visualize my ideas, and I will put the zip file here! But i'm going to explain them here as well.
My favorite idea was with the ultimate miner chapter, I think it would be cool if it worked more like an "museum" of sorts, where you have to get a bit of each ore and submit them to the "Museum" (alongside other things like pickaxes and blocks). I had an similar idea for the "kill a bunch of mobs" chapter, which would work like an bestiary, but I didn't remade that chapter yet.
My other idea I liked was with the completion quests. If you do every quest in a chapter, you get an very special and powerful item. For exemple, the completion item for the ultimate miner chapter is the jackhammer. Maybe the story mode armors could be completion items as well!
I also tried to make the first chapter to be more like an complete tutorial, and some quests lead the player to some important mods, like farmer's delight and tom's simple storage mod. I also had an idea of adding some quests teaching the player about the keybinds and etc, but I ended up not adding that.
For the other chapters, I just tried to make them look a bit more pretty! I used different shapes and sizes for important quests and variation. I didn't add rewards for most of the quests tho, but I DID tried to name most of them.
Here's the zip file with the 6 chapters I tried to remake:

[quests.zip](https://github.com/kyber-6/fantasymc-fabric-modpack/files/12524995/quests.zip)

**Comment by KevzCz** [comment]
Thanks!
